urls:
  principal: https://www.google.com

timeouts:
  light: <%= ENV['LIGHT_TIMEOUT'] || 1 %>
  short: <%= ENV['SHORT_TIMEOUT'] || 5 %>
  medium: <%= ENV['MEDIUM_TIMEOUT'] || 10 %>
  long: <%= ENV['LONG_TIMEOUT'] || 15 %>